"""
LLM Insights — cross-continent player development (Groq / OpenAI + offline fallback)
===================================================================================
Given a player's attribute profile, produce development guidance informed by
coaching strategies from other football continents.

  * If GROQ_API_KEY or OPENAI_API_KEY is set (and the `openai` package is
    installed), the advice is generated by the LLM, GROUNDED in
    continental_strategies so it stays anchored to real coaching philosophies.
  * Otherwise it transparently falls back to the offline knowledge-base insight.

Groq is OpenAI-API-compatible, so we use the same `openai` client pointed at
Groq's endpoint. Keys are read from the environment — never passed through the
app or logged here. Configure on your machine / Render:

    # Groq (preferred if set) — get a free key at console.groq.com
    GROQ_API_KEY=gsk_...
    GROQ_MODEL=llama-3.3-70b-versatile   (optional; default shown)

    # or OpenAI
    OPENAI_API_KEY=sk-...
    OPENAI_MODEL=gpt-4o-mini             (optional; default shown)
"""

import os
from continental_strategies import offline_insight, PHILOSOPHIES

GROQ_BASE_URL = "https://api.groq.com/openai/v1"
DEFAULT_GROQ_MODEL = "llama-3.3-70b-versatile"
DEFAULT_OPENAI_MODEL = "gpt-4o-mini"


def _provider():
    """Return (name, api_key, base_url, model) for whichever LLM is configured."""
    if os.environ.get("GROQ_API_KEY"):
        return ("groq", os.environ["GROQ_API_KEY"], GROQ_BASE_URL,
                os.environ.get("GROQ_MODEL", DEFAULT_GROQ_MODEL))
    if os.environ.get("OPENAI_API_KEY"):
        return ("openai", os.environ["OPENAI_API_KEY"], None,
                os.environ.get("OPENAI_MODEL", DEFAULT_OPENAI_MODEL))
    return (None, None, None, None)

SYSTEM_PROMPT = (
    "You are a youth football development analyst for a grassroots academy. "
    "You give specific, practical development advice grounded in real coaching "
    "philosophies from different football continents (e.g. Spanish positional "
    "play, Brazilian futsal technique, German gegenpressing, Italian defending, "
    "African athleticism). Be concise and concrete. Only use the player facts "
    "you are given — do not invent statistics or biography."
)


def llm_configured():
    return _provider()[0] is not None


def _build_prompt(player, role, attributes, weaknesses, strengths, base):
    lines = [f"Player: {player}", f"Best role: {role}"]
    if attributes:
        lines.append("Attribute scores (0-100): " +
                     ", ".join(f"{a} {v:.0f}" for a, v in
                               sorted(attributes.items(), key=lambda x: x[1])))
    if strengths:
        lines.append("Strengths: " + ", ".join(strengths))
    if weaknesses:
        lines.append("Weaknesses: " + ", ".join(weaknesses))
    # ground the model in our knowledge base
    if base.get("focus_items"):
        lines.append("\nReference coaching strategies to draw from:")
        for it in base["focus_items"]:
            lines.append(f"- {it['attribute']}: study {', '.join(it['study'])} — {it['approach']}")
    lines.append(
        "\nWrite a short cross-continent development plan (3-4 sentences) for this "
        "player, then 3 bullet-point training recommendations that reference the "
        "relevant football cultures. Keep it practical for a grassroots coach."
    )
    return "\n".join(lines)


def verify_players(names):
    """Ask the LLM whether each string is a plausible PERSON'S NAME (a player),
    versus a non-name wrongly picked up from commentary (a common word, a football
    term, a team/club name, an action). Grassroots/unknown players still count as
    names — we only weed out non-names.
    Returns {name: 'real' | 'unknown' | 'unverified'}.
      real       = plausible player name (keep)
      unknown    = not a player name (drop as unnecessary string)
      unverified = no LLM configured (can't check, keep)."""
    names = [n for n in (names or []) if n and n.strip()]
    if not names:
        return {}
    provider_name, api_key, base_url, default_model = _provider()
    if provider_name is None:
        return {n: "unverified" for n in names}
    try:
        import json as _json
        from openai import OpenAI
        client = OpenAI(api_key=api_key, base_url=base_url)
        listing = "\n".join(f"- {n}" for n in names)
        prompt = (
            "These strings were auto-extracted from football commentary as candidate "
            "player names. For EACH item, reply true if it is a plausible PERSON'S NAME "
            "of a footballer (UNKNOWN or grassroots players are fine — judge only whether "
            "it looks like a person's name), or false if it is clearly NOT a person's name "
            "— e.g. a common English word, a football term (penalty, goal, corner, offside), "
            "a team or club name, or a non-name fragment. Reply ONLY with a JSON object "
            "mapping each exact string to true or false.\n\n" + listing
        )
        resp = client.chat.completions.create(
            model=default_model,
            messages=[{"role": "system", "content": "You are a football knowledge checker. Reply only with JSON."},
                      {"role": "user", "content": prompt}],
            temperature=0.0, max_tokens=400,
        )
        txt = resp.choices[0].message.content.strip()
        # strip code fences if present
        if txt.startswith("```"):
            txt = txt.strip("`")
            txt = txt[txt.find("{"):txt.rfind("}") + 1]
        else:
            txt = txt[txt.find("{"):txt.rfind("}") + 1]
        parsed = _json.loads(txt)
        out = {}
        low = {k.lower(): v for k, v in parsed.items()}
        for n in names:
            v = parsed.get(n, low.get(n.lower()))
            out[n] = ("real" if v else "unknown") if v is not None else "unverified"
        return out
    except Exception:
        return {n: "unverified" for n in names}


def continental_insight(player, role, attributes, weaknesses=None, strengths=None, model=None):
    """Return a development-insight dict. Uses OpenAI if configured, else offline."""
    base = offline_insight(player, role, attributes, weaknesses, strengths)

    name, api_key, base_url, default_model = _provider()
    if name is None:
        base["mode"] = "offline (no GROQ_API_KEY / OPENAI_API_KEY set)"
        return base

    try:
        from openai import OpenAI
        client = OpenAI(api_key=api_key, base_url=base_url)  # base_url=None -> OpenAI
        use_model = model or default_model
        prompt = _build_prompt(player, role, attributes, weaknesses, strengths, base)
        resp = client.chat.completions.create(
            model=use_model,
            messages=[{"role": "system", "content": SYSTEM_PROMPT},
                      {"role": "user", "content": prompt}],
            temperature=0.4, max_tokens=550,
        )
        base["source"] = name
        base["mode"] = f"{name.capitalize()} ({use_model})"
        base["llm_text"] = resp.choices[0].message.content.strip()
        return base
    except Exception as e:
        base["mode"] = f"offline ({name} error: {type(e).__name__})"
        base["note"] = (f"Could not reach {name}; showing offline knowledge-base "
                        f"insight. Check the API key, model name, and that `openai` "
                        f"is installed. [{e}]")
        return base
