"""
LLM Insights — cross-continent player development (OpenAI + offline fallback)
============================================================================
Given a player's attribute profile, produce development guidance informed by
coaching strategies from other football continents.

  * If OPENAI_API_KEY is set (and the `openai` package is installed), the advice
    is generated by OpenAI, GROUNDED in continental_strategies so it stays
    anchored to real coaching philosophies.
  * Otherwise it transparently falls back to the offline knowledge-base insight.

The API key is read from the environment by the OpenAI SDK — it is never passed
through the app or logged here. Configure it on your machine / Render:
    OPENAI_API_KEY=sk-...        (required for the LLM path)
    OPENAI_MODEL=gpt-4o-mini     (optional; default gpt-4o-mini)
"""

import os
from continental_strategies import offline_insight, PHILOSOPHIES

SYSTEM_PROMPT = (
    "You are a youth football development analyst for a grassroots academy. "
    "You give specific, practical development advice grounded in real coaching "
    "philosophies from different football continents (e.g. Spanish positional "
    "play, Brazilian futsal technique, German gegenpressing, Italian defending, "
    "African athleticism). Be concise and concrete. Only use the player facts "
    "you are given — do not invent statistics or biography."
)


def llm_configured():
    return bool(os.environ.get("OPENAI_API_KEY"))


def _build_prompt(player, role, attributes, weaknesses, strengths, base):
    lines = [f"Player: {player}", f"Best role: {role}"]
    if attributes:
        lines.append("Attribute scores (0-100): " +
                     ", ".join(f"{a} {v:.0f}" for a, v in
                               sorted(attributes.items(), key=lambda x: x[1])))
    if strengths:
        lines.append("Strengths: " + ", ".join(strengths))
    if weaknesses:
        lines.append("Weaknesses: " + ", ".join(weaknesses))
    # ground the model in our knowledge base
    if base.get("focus_items"):
        lines.append("\nReference coaching strategies to draw from:")
        for it in base["focus_items"]:
            lines.append(f"- {it['attribute']}: study {', '.join(it['study'])} — {it['approach']}")
    lines.append(
        "\nWrite a short cross-continent development plan (3-4 sentences) for this "
        "player, then 3 bullet-point training recommendations that reference the "
        "relevant football cultures. Keep it practical for a grassroots coach."
    )
    return "\n".join(lines)


def continental_insight(player, role, attributes, weaknesses=None, strengths=None, model=None):
    """Return a development-insight dict. Uses OpenAI if configured, else offline."""
    base = offline_insight(player, role, attributes, weaknesses, strengths)

    if not llm_configured():
        base["mode"] = "offline (no OPENAI_API_KEY set)"
        return base

    try:
        from openai import OpenAI
        client = OpenAI()  # reads OPENAI_API_KEY from env
        model = model or os.environ.get("OPENAI_MODEL", "gpt-4o-mini")
        prompt = _build_prompt(player, role, attributes, weaknesses, strengths, base)
        resp = client.chat.completions.create(
            model=model,
            messages=[{"role": "system", "content": SYSTEM_PROMPT},
                      {"role": "user", "content": prompt}],
            temperature=0.4, max_tokens=550,
        )
        base["source"] = "openai"
        base["mode"] = f"OpenAI ({model})"
        base["llm_text"] = resp.choices[0].message.content.strip()
        return base
    except Exception as e:
        base["mode"] = f"offline (LLM error: {type(e).__name__})"
        base["note"] = ("Could not reach OpenAI; showing offline knowledge-base "
                        "insight. Check OPENAI_API_KEY and that `openai` is installed.")
        return base
